### ISSUE TITLE
create-react-app vs react-js-vector-icon

### ISSUE THREAD

**Issue by aprather51** [sturmenta/react-web-vector-icons#1]
Following steps...

2 - Add require of fonts for webpack in your index.js file
```js
require('react-js-vector-icons/fonts');
```
How could this achieve when using create-react-app without ejection?  Perhaps could we use this method ??
```js
import Icon, { Octagon } from 'react-js-vector-icons/fonts';
```

**Comment by sturmenta** [comment]
@aprather51 What do you mean by "without ejection"?

Sorry for delaying so much in answering, being honest I must have overlooked the issue

<img src='https://media.giphy.com/media/HyCxJErg9jTCU/giphy.gif'>
