### ISSUE TITLE
Support FontAwesome5

### ISSUE THREAD

**Issue by bosung90** [sturmenta/react-web-vector-icons#2]
react-native-vector-icons support new set of fonts including FontAwesome5.

Is it possible for this font to be supported in react-web-vector-icons as well?

Thanks.

**Comment by badaz** [comment]
Hello, thanks for the lib! Is there some kind of difference in implementation that would explain why you did not add support for FontAwesome5 in the first place?

**Comment by badaz** [comment]
Maybe because FontAwesome5 was introduced in rn-vector-icons after this lib was created, right?
