### ISSUE TITLE
Icons not properly getting displayed

### ISSUE THREAD

**Issue by Hamza-Khurshid** [sturmenta/react-web-vector-icons#7]
I've installed "react-web-vector-icons" to use icons. I've also included <style> in index.html and require in index.js file. But when I try too use any icon the icon displays in rectangle form. 
Like this []

**Comment by ashertoufeeq** [comment]
i am also having the same issue

**Comment by WintelZhao** [comment]
The same issue.

**Comment by codedadysolutions** [comment]
i am also having the issue

**Comment by vantb9x** [comment]
The same issue.

**Comment by italosena9** [comment]
Look how is the package.json of the included "test" project. You need webpack and Babel, plus the extra dependencies.

Installing and configuring then all icons will appear

**Comment by Frekansapp** [comment]
@italosena9 Can you be more descriptive?

**Comment by Frekansapp** [comment]
The same issue. I also try install  "devDependencies": {
    "babel-core": "^6.26.3",
    "babel-eslint": "^10.0.1",
    "babel-loader": "^7.1.5",
    "babel-preset-env": "^1.7.0",
    "babel-preset-react": "^6.24.1",
    "eslint": "^5.6.1",
    "eslint-plugin-react": "^7.11.1",
    "file-loader": "^2.0.0",
    "html-webpack-plugin": "^3.2.0",
    "react-web-vector-icons": "1.0.0",
    "webpack": "^4.20.2",
    "webpack-cli": "^3.1.2",
    "webpack-dev-server": "^3.1.11"
  }
this devDependencies but not working

**Comment by italosena9** [comment]
In your root folder copy paste the file ".babelrc" and "webpack.config", in package.json configure the script part, devDependencies and dependencies according to the example. If you need to make any changes or rules, do it in webpack. Install the dependencies with "npm" or in my case "yarn"

**Comment by FoodlyEric** [comment]
how do I make this work in create-react-app?

**Comment by sturmenta** [comment]
@FoodlyEric with these steps you can use react-native-vector-icons in an app with create-react-app https://gist.github.com/sturmenta/246e8cb61dc891a29f8a36eceb55d529

**Comment by sturmenta** [comment]
As @italosena9 said the configuration for webpack and babel is in the [usage example](https://github.com/sturmenta/react-web-vector-icons/tree/master/test)
